### ISSUE TITLE
Agora can get stuck trying to restart

### ISSUE THREAD

**Issue by Geod24** [bosagora/agora#1388]
```
Nov 27 11:00:25 eu-002 docker[6565]: 2020-11-27 11:00:25,939 Info [agora.common.TransactionPool] - Loading database fro
Nov 27 11:00:25 eu-002 docker[6565]: 2020-11-27 11:00:25,939 Info [agora.common.TransactionPool] - Loaded database from
Nov 27 11:00:25 eu-002 docker[6565]: 2020-11-27 11:00:25,940 Info [agora.consensus.state.UTXODB] - Loading UTXO databas
Nov 27 11:00:25 eu-002 docker[6565]: 2020-11-27 11:00:25,940 Info [agora.consensus.state.UTXODB] - Loaded database from
Nov 27 11:00:25 eu-002 docker[6565]: 2020-11-27 11:00:25,944 Fatal [agora.node.Ledger] - Error while adding a new valid
Nov 27 11:00:25 eu-002 docker[6565]: 2020-11-27 11:00:25,944 Fatal [agora.node.Ledger] - Enrollment #0: { utxo_key: 0x4
Nov 27 11:00:25 eu-002 docker[6565]: 2020-11-27 11:00:25,945 Fatal [agora.node.Ledger] - Validated block: { header: { p
Nov 27 11:00:25 eu-002 docker[6565]: core.exception.AssertError@source/agora/node/Ledger.d(415): Assertion failure
```

Probably introduced by https://github.com/bpfkorea/agora/pull/1379 looking at the failure.

**Comment by kchulj** [comment]
A similar behavior was observed in #1367 .

**Comment by Geod24** [comment]
This actually triggers just trying to restart a perfectly working Agora. So restart is completely broken.

**Comment by Geod24** [comment]
```gdb
Breakpoint 1, agora.node.Ledger.Ledger.updateValidatorSet(ref const(agora.consensus.data.Block.Block)) (this=0x7fe024e9a000,
    block=...) at /root/agora/source/agora/node/Ledger.d:415
415     /root/agora/source/agora/node/Ledger.d: No such file or directory.
(gdb) bt
#0  agora.node.Ledger.Ledger.updateValidatorSet(ref const(agora.consensus.data.Block.Block)) (this=0x7fe024e9a000, block=...)
    at /root/agora/source/agora/node/Ledger.d:415
#1  0x0000558a7d83a227 in agora.node.Ledger.Ledger.this(immutable(agora.consensus.data.Params.ConsensusParams), agora.consensus.state.UTXODB.UTXOSet, agora.node.BlockStorage.IBlockStorage, agora.consensus.EnrollmentManager.EnrollmentManager, agora.common.TransactionPool.TransactionPool, agora.node.Fee.DataPayloadChecker, void(ref const(agora.consensus.data.Block.Block), bool) @safe delegate) (
    this=0x7fe024e9a000, params=0x7fe024e7de60, utxo_set=0x7fe024e90880, storage=0x7fe024e93690, enroll_man=0x7fe024e8ca00,
    pool=0x7fe024e90680, payload_checker=0x7fe024e7ce40, onAcceptedBlock=...) at /root/agora/source/agora/node/Ledger.d:199
#2  0x0000558a7d830257 in agora.node.FullNode.FullNode.this(const(agora.common.Config.Config)) (this=0x7fe024e94000, config=...)
    at /root/agora/source/agora/node/FullNode.d:181
#3  0x0000558a7d82f8d6 in agora.node.Validator.Validator.this(const(agora.common.Config.Config)) (this=0x7fe024e94000, config=...)
    at /root/agora/source/agora/node/Validator.d:91
#4  0x0000558a7d82ddee in agora.node.Runner.runNode(agora.common.Config.Config) (config=...)
    at /root/agora/source/agora/node/Runner.d:71
#5  0x0000558a7d82dac5 in agora.node.main.main(immutable(char)[][]).__lambda3() () at /root/agora/source/agora/node/main.d:100
#6  0x0000558a7d98dc40 in vibe.core.task.TaskFuncInfo.set!(std.typecons.Tuple!(agora.node.FullNode.FullNode, "node", vibe.http.server.HTTPListener, "http_listener").Tuple() delegate).set(ref std.typecons.Tuple!(agora.node.FullNode.FullNode, "node", vibe.http.server.HTTPListener, "http_listener").Tuple() delegate).callDelegate(ref vibe.core.task.TaskFuncInfo) (tfi=...)
    at /root/agora/submodules/vibe-core/source/vibe/core/task.d:712
#7  0x0000558a7dc05212 in vibe.core.task.TaskFuncInfo.call() (this=0x0) at task.d:730
#8  0x0000558a7dc04a27 in vibe.core.task.TaskFiber.run() (this=0x7fe024e92600) at task.d:439
#9  0x00007fe0250495d3 in fiber_entryPoint () from /usr/lib/libdruntime-ldc-shared.so.90
#10 0x0000000000000000 in ?? ()
```

**Comment by kchulj** [comment]
Is it a bug in agora or upstream?

**Comment by hewison-chris** [comment]
Looks like a bug in Agora. The ValidatorSe table (file) is not existing in this scenario.

**Comment by Geod24** [comment]
Part of the fix is in https://github.com/bpfkorea/agora/pull/1390 and it's an agora bug

**Comment by Geod24** [comment]
Confirmed fixed
